services:
    _defaults:
        autoconfigure: true

    Oveleon\ContaoCookiebar\Controller\ContentElement\CookiebarOpenerController: ~

    Oveleon\ContaoCookiebar\Controller\FrontendModule\CookiebarOpenerController: ~

    Oveleon\ContaoCookiebar\Controller\CookiebarController:
        public: true
        arguments:
            - '@contao.framework'
            - '@translator'
