services:
    _defaults:
        autoconfigure: true

    contao_cookiebar.migration.consent_mode_migration:
        class: Oveleon\ContaoCookiebar\Migration\ConsentModeMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    contao_cookiebar.migration.cookiebar_opener_migration:
        class: Oveleon\ContaoCookiebar\Migration\CookiebarOpenerMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
