services:
    _defaults:
        autoconfigure: true

    contao_cookiebar.insert_tag.cookiebar:
        class: Oveleon\ContaoCookiebar\InsertTag\CookiebarInsertTag
        arguments:
            - '@translator'
