name: CI

on:
    pull_request: ~

permissions: read-all

defaults:
    run:
        # Simulate an interactive terminal with color support
        shell: script -q -e -c "export TERM=xterm; bash {0}"

jobs:
    yamllint:
        name: YAMLlint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

    linter:
        name: Linter
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install the Node packages
              run: npm install

            - name: Run Biome
              run: npx biome ci core-bundle/assets

            - name: Run Stylelint
              run: npx stylelint --fix core-bundle/assets/styles
